### ISSUE TITLE
Please remove unnecessary resources (test.png)

### ISSUE THREAD

**Issue by Robby3St** [Makeandbreak09/Chess-AI#1]
Hey Makeandbreak,
it would be nice to keep the project very simple with only the necessary required resources. This includes, removing the unnecassary image test.png, which would make the project such nicer as a very fast and lightweight repository :D

**Comment by Makeandbreak09** [comment]
Yeah, for sure, no worries. We am just really busy at the moment, but will get right back on it, when we find the time for it.
